// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu_cO6F6Q9-TfTL4pJGo6TlHGbVvRYydI',
    appId: '1:151779621550:web:0bfa0504528ca8bdc00b3f',
    messagingSenderId: '151779621550',
    projectId: 'test-iti',
    authDomain: 'test-iti.firebaseapp.com',
    storageBucket: 'test-iti.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASUibDN5x7qVrZKjxIE0O532GUQllNE6M',
    appId: '1:151779621550:android:5d8e4b2b86f4e0cbc00b3f',
    messagingSenderId: '151779621550',
    projectId: 'test-iti',
    storageBucket: 'test-iti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvJUIBTvfmLLTCRxInfQajKYjk-wEzmig',
    appId: '1:151779621550:ios:e0600dff1f074795c00b3f',
    messagingSenderId: '151779621550',
    projectId: 'test-iti',
    storageBucket: 'test-iti.firebasestorage.app',
    iosBundleId: 'com.example.signUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvJUIBTvfmLLTCRxInfQajKYjk-wEzmig',
    appId: '1:151779621550:ios:e0600dff1f074795c00b3f',
    messagingSenderId: '151779621550',
    projectId: 'test-iti',
    storageBucket: 'test-iti.firebasestorage.app',
    iosBundleId: 'com.example.signUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu_cO6F6Q9-TfTL4pJGo6TlHGbVvRYydI',
    appId: '1:151779621550:web:52d93040e2790454c00b3f',
    messagingSenderId: '151779621550',
    projectId: 'test-iti',
    authDomain: 'test-iti.firebaseapp.com',
    storageBucket: 'test-iti.firebasestorage.app',
  );

}